name: ValueSet $validate-code an existing code in 'Australian Immunisation Register Vaccine' CodeSystem

on: 
  [push, pull_request]
  
jobs:

  ValueSet-validate-code:

    runs-on: ubuntu-latest

    steps:
      
      - name: check out repo under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: POST to http://tx.fhir.org
        id: request
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.5
        
        with:
          url: 'http://tx.fhir.org/r4/ValueSet/$validate-code'
          method: 'POST'
          contentType: 'application/fhir+json'
          file: "${{ github.workspace }}/REST/parameter-air-validate-code-pass.json"

      - name: Print the response payload
        run: echo ${{ steps.request.outputs.response }}
        shell: bash

      - name: Check response
        env:
          RESULT: ${{ fromJson(steps.request.outputs.response).parameter[3].valueBoolean }}
        if: ${{ env.RESULT != 'true' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('The FHIR server response is not result = true!')